---
- name: Sync versions to upstream and template files
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Check for updates
    ansible.builtin.shell: pwd && ./hack/check-versions.sh check-update all > .version-check
    args:
      chdir: "{{ playbook_dir }}/.."

  - name: Read in if those versions have updates
    ansible.builtin.include_vars:
      file: ../.version-check
      name: updates_available

  - name: Get update versions
    ansible.builtin.shell: ./hack/check-versions.sh latest-version all > .version-check
    args:
      chdir: "{{ playbook_dir }}/.."

  - name: Read in if those versions have updates
    ansible.builtin.include_vars:
      file: ../.version-check
      name: latest_version

  - name: Version detection results
    ansible.builtin.debug:
      msg:
        - "Updates available:"
        - "  cloudflared: {{ updates_available.cloudflared }}"
        - "  uptimekuma: {{ updates_available.uptimekuma }}"
        - "  baseimage: {{ updates_available.baseimage }}"
        - ""
        - "Latest versions:"
        - "  cloudflared: {{ latest_version.cloudflared }}"
        - "  uptimekuma: {{ latest_version.uptimekuma }}"
        - "  baseimage: {{ latest_version.baseimage }}"
      

  - name: Template out the Dockerfile
    when: updates_available.cloudflared|bool or updates_available.uptimekuma|bool or updates_available.baseimage|bool
    ansible.builtin.template:
      src: templates/Dockerfile.j2
      dest: Dockerfile



  - name: Toucha file
    ansible.builtin.file:
      path: "{{ playbook_dir }}/../test"
      state: touch
